### ISSUE TITLE
route.currentRule returns undefined

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/can-route#151]
I have a component that is rendered for a specific route. This works. During the component render I am logging the value of `route.currentRoute()`, and it is undefined. I am using `can-route-pushstate@4.0.1`.

**Comment by justinbmeyer** [comment]
Can you give an example?

**Comment by DesignByOnyx** [comment]
https://github.com/DesignByOnyx/can-route-bug

**Comment by justinbmeyer** [comment]
Where is `route.currentRoute()` being called @DesignByOnyx ?

**Comment by justinbmeyer** [comment]
I think it's now: https://canjs.com/doc/can-route.currentRule.html

**Comment by m-mujica** [comment]
A couple of issues with the sample app:

1. Since assets are in the public folder, `pushstate.root` has to be set to `/public/`
2. There was an issues in can-route-pushstate preventing observables to know when `currentRule` was read. Fix -> https://github.com/canjs/can-route-pushstate/pull/92
3. The default route `"/"` will have a `currentRule() === ""` @justinbmeyer explained to me why we should avoid doing `route.register("/")` but I forgot 😬 

I'm going to close this issues once the can-route-pushstate fix lands.

**Comment by m-mujica** [comment]
https://github.com/canjs/can-route-pushstate/releases/tag/v4.0.4
