### ISSUE TITLE
Elegantly handle can-route.map(defineMap) needing a route property. ~13

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route#21]
From https://github.com/canjs/canjs/issues/2465

There are several options.  I'll start with the hardest, but nicest.

With my recent changes to can-define to support inheritance, it should be possible to dynamically add a `route` property.   

 - If an instance of `defineMap` is passed, we should still be able to add a route property to its `defineMap.constructor.prototype`.  In this case, we should `console.warn` that the person should probably define a route property themselves.

- If a `DefineMap` type is passed, we certainly can add a property to `DefineMap.prototype`.

To support this, we probably need an issue that adds this ability to `DefineMap`.  Something like `DefineMap.addProp( name, propertyDescription )` 

If this doesn't work, we can simply check if the map is sealed and the `route` property isn't defined ... if this is the case ... throw a nice warning.

**Comment by matthewp** [comment]
I don't think a warning is appropriate in this case. A warning is meant to convey that there is future danger. A caution light at an intersection tells you that the light is about to turn red and that you should slow down.

Reasons to have warnings in a library include:

* A deprecated API that will be removed in the future.
* An API with known performance problems.

There are probably more that I can't think of off the top of my heading, but the key is that something bad will (eventually) happen if you don't change your code.

Warnings are *not* for best-practices advice.  In this case I think defining a "route" property is a good idea, I don't feel super strong about it though, so I think we should do either one of two things:

1. Leave the warning out and provide the best-practices advice in the documentation.
2. Throw an error instead of a warning. This error would be most specific than the one you currently get from can-define in this case.

**Comment by justinbmeyer** [comment]
I'm fine throwing an error.
